name: operating_modes
channels:
  - conda-forge
dependencies:
  - python=3.13
  - cadet>=5.1,<6.0
  - openssh
  - git
  - git-lfs
  - pip
  - pip:
    - cadet-rdm>=1.1.0
    - cadet-process>=0.11,<1.0
